sudo: false   # Use container-based infrastructure.
language: python

# Create a test environment and install dependencies.
install: source continuous_integration/install.sh
# Command to run tests.
script: pytest
